name: Node.js CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_SUPABASE_URL: ${{ secrets.REACT_APP_SUPABASE_URL }}
      REACT_APP_SUPABASE_KEY: ${{ secrets.REACT_APP_SUPABASE_KEY }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: yarn install --immutable --immutable-cache --check-cache
    - run: yarn run test
      env:
        CI: true